from pathlib import Path
p = Path('Runtime/KairoRenderBridge/SceneSnapshotBridge.cppm')
s = p.read_text()
old_fog = '''            if (environment.Fog != engine::FogMode::Disabled)\n                detail::AddDiagnostic(result, DiagnosticSeverity::Error, *environmentEntity,\n                    "fog-unsupported", "Offline ray tracing does not yet implement EngineCore fog semantics.");'''
new_fog = '''            result.Snapshot.Settings.FogColor = detail::ToColor(environment.FogColor);\n            result.Snapshot.Settings.FogDensity = environment.FogDensity;\n            result.Snapshot.Settings.FogNear = environment.FogNear;\n            result.Snapshot.Settings.FogFar = environment.FogFar;\n            switch (environment.Fog)\n            {\n                case engine::FogMode::Disabled:\n                    result.Snapshot.Settings.Fog = ray::FogMode::Disabled;\n                    break;\n                case engine::FogMode::Linear:\n                    result.Snapshot.Settings.Fog = ray::FogMode::Linear;\n                    break;\n                case engine::FogMode::Exponential:\n                    result.Snapshot.Settings.Fog = ray::FogMode::Exponential;\n                    break;\n            }'''
if old_fog not in s: raise SystemExit('fog diagnostic block not found')
s = s.replace(old_fog, new_fog)
old_lights = '''                case engine::LightType::Directional:\n                    detail::AddDiagnostic(result, DiagnosticSeverity::Error, entity,\n                        "directional-light-unsupported",\n                        "The current CPU ray tracer has no directional-light emitter; rendering is blocked rather than approximated.");\n                    break;\n                case engine::LightType::Spot:\n                    detail::AddDiagnostic(result, DiagnosticSeverity::Error, entity,\n                        "spot-light-unsupported",\n                        "The current CPU ray tracer has no spot-light emitter; rendering is blocked rather than approximated.");\n                    break;'''
new_lights = '''                case engine::LightType::Directional:\n                {\n                    ray::DirectionalLight directional;\n                    directional.Direction = world.Forward();\n                    directional.Color = detail::ToColor(light.Color);\n                    directional.Illuminance = light.Intensity;\n                    result.Snapshot.DirectionalLights.push_back(directional);\n                    break;\n                }\n                case engine::LightType::Spot:\n                {\n                    ray::SpotLight spot;\n                    spot.Position = world.Translation;\n                    spot.Direction = world.Forward();\n                    spot.Color = detail::ToColor(light.Color);\n                    spot.Intensity = light.Intensity;\n                    spot.Range = light.Range;\n                    spot.InnerConeCosine = std::cos(light.InnerConeRadians);\n                    spot.OuterConeCosine = std::cos(light.OuterConeRadians);\n                    result.Snapshot.SpotLights.push_back(spot);\n                    break;\n                }'''
if old_lights not in s: raise SystemExit('unsupported light block not found')
s = s.replace(old_lights, new_lights)
p.write_text(s)

p = Path('Runtime/KairoRenderBridge/tests/SceneSnapshotBridgeTests.cpp')
s = p.read_text()
start = '''TEST_CASE("Unsupported authored light semantics block render before launch")\n'''
if start in s:
    a = s.index(start)
    b = s.index('TEST_CASE("Offline render session writes project-owned result metadata")', a)
    replacement = '''TEST_CASE("directional spot and fog semantics convert into the shared offline scene")\n{\n    using namespace kairo::engine;\n    using namespace kairo::runtime::renderbridge;\n    Scene scene = MakeRenderableScene();\n\n    const Entity sun = scene.CreateEntity("Sun");\n    LightComponent directional;\n    directional.Type = LightType::Directional;\n    directional.Unit = PhotometricUnit::Lux;\n    directional.Intensity = 3.0f;\n    scene.SetLight(sun, directional);\n\n    const Entity spotEntity = scene.CreateEntity("Spot");\n    LightComponent spot;\n    spot.Type = LightType::Spot;\n    spot.Unit = PhotometricUnit::Candela;\n    spot.Intensity = 8.0f;\n    spot.Range = 25.0f;\n    spot.InnerConeRadians = 0.25f;\n    spot.OuterConeRadians = 0.5f;\n    scene.SetLight(spotEntity, spot);\n    scene.Transform(spotEntity).Local.Translation = { 0.0f, 2.0f, 3.0f };\n\n    const Entity environmentEntity = scene.CreateEntity("Environment");\n    EnvironmentComponent environment;\n    environment.Active = true;\n    environment.Fog = FogMode::Exponential;\n    environment.FogColor = { 0.1f, 0.2f, 0.3f };\n    environment.FogDensity = 0.04f;\n    scene.SetEnvironment(environmentEntity, environment);\n\n    const auto converted = ConvertSceneSnapshot(scene, {});\n    REQUIRE(converted.Supported());\n    REQUIRE(converted.Snapshot.DirectionalLights.size() == 1u);\n    REQUIRE(converted.Snapshot.SpotLights.size() == 1u);\n    CHECK(converted.Snapshot.DirectionalLights.front().Illuminance == 3.0f);\n    CHECK(converted.Snapshot.SpotLights.front().Intensity == 8.0f);\n    CHECK(converted.Snapshot.SpotLights.front().Range == 25.0f);\n    CHECK(converted.Snapshot.Settings.Fog == kairo::foundation::raytracer::FogMode::Exponential);\n    CHECK(converted.Snapshot.Settings.FogDensity == 0.04f);\n}\n\n'''
    s = s[:a] + replacement + s[b:]
p.write_text(s)

p = Path('Runtime/KairoRenderBridge/tests/EditorOfflineRenderServiceTests.cpp')
s = p.read_text()
start = '''TEST_CASE("editor offline service reports unsupported scene semantics before starting worker")\n'''
if start in s:
    a = s.index(start)
    # replace through EOF for second test in current file
    replacement = '''TEST_CASE("editor offline service accepts directional authored lighting")\n{\n    using namespace kairo::engine;\n    using namespace kairo::editor;\n    using namespace kairo::runtime::renderbridge;\n\n    Scene scene;\n    const Entity cameraEntity = scene.CreateEntity("Camera");\n    CameraComponent camera; camera.Primary = true;\n    scene.SetCamera(cameraEntity, camera);\n    scene.Transform(cameraEntity).Local.Translation = { 0.0f, 0.0f, 4.0f };\n    const Entity sun = scene.CreateEntity("Sun");\n    LightComponent light;\n    light.Type = LightType::Directional;\n    light.Unit = PhotometricUnit::Lux;\n    light.Intensity = 2.0f;\n    scene.SetLight(sun, light);\n\n    const auto root = std::filesystem::temp_directory_path() / "kairo-editor-offline-directional-test";\n    std::filesystem::remove_all(root);\n    std::filesystem::create_directories(root / "Renders");\n    EditorOfflineRenderService service([&]() -> const Scene& { return scene; }, {});\n    OfflineRenderRequest request;\n    request.JobID = 102u; request.Width = 4u; request.Height = 4u; request.Passes = 1u;\n    request.ProjectRoot = root; request.RelativeOutput = "Renders/directional.ppm";\n    service.Submit(request);\n    auto progress = service.Poll(request.JobID);\n    CHECK(progress.Status != OfflineRenderWorkspaceStatus::Failed);\n    service.Cancel(request.JobID);\n    std::filesystem::remove_all(root);\n}\n'''
    s = s[:a] + replacement
p.write_text(s)

Path('.github/workflows/map-full-offline-scene-semantics.yml').unlink()
Path('.github/scripts/map_full_offline_scene_semantics.py').unlink()
